name: Run tests on main

on:
  push:
    branches:
      - feature

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Different steps for the feature branch
      - name: Run different tests - FEATURE
        run: echo "Running tests for FEATURE"
