name: Run tests on feature

on:
  push:
    branches:
      - feature
  pull_request:
    branches:
      - feature

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Different steps for the feature branch
      - name: Run different tests
        run: echo "Running tests for feature branch"
