name: Run tests on main

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Additional steps for the main branch
      - name: Run tests
        run: echo "Running tests for main branch"
